// This file is autogenerated. Edit Mathx_ScalarFunctions.tt instead.
namespace AntilatencyMath {

    using T = System.Single;

    public static partial class Mathx {

        public static T abs(T x) {
            return (T)System.Math.Abs(x);
        }

        public static T sqr(T x) {
            return x * x;
        }

        public static T sqrt(T x) {
            return (T)System.Math.Sqrt(x);
        }

        public static T exp(T x) {
            return (T)System.Math.Exp(x);
        }

        public static T log(T x) {
            return (T)System.Math.Log(x);
        }

        public static T sin(T x) {
            return (T)System.Math.Sin(x);
        }

        public static T cos(T x) {
            return (T)System.Math.Cos(x);
        }

        public static T tan(T x) {
            return (T)System.Math.Tan(x);
        }


        public static T plus(T a, T b) {
            return a + b;
        }

        public static T minus(T a, T b) {
            return a - b;
        }

        public static T atan2(T a, T b) {
            return (T)System.Math.Atan2(a, b);
        }

        public static T pow(T a, T b) {
            return (T)System.Math.Pow(a, b);
        }

    }
}
